<?php
session_start();
$LoggedUser=$_GET['user'];
if($LoggedUser=='admin'){
    session_destroy();
    header('location:../admin_signin.html');
}
else{
    session_destroy();
    header('location:../user_signin.html');
}
?>
